In [42]:
import pandas as pd
import numpy as np

datain_dir = "~/Desktop/python/Data Mining Project/ReadmissionAnalytics/"
df_raw = pd.read_csv(datain_dir + "diabetic_data.csv")

df_raw = df_raw.replace('?', np.nan)

# Column details
col_data = df_raw.apply(lambda s: set(s.unique()), axis=0).to_frame('uni_val')
col_data['nan_rat'] = df_raw.isnull().sum(axis=0)/len(df_raw)
col_data['n_uni_vals'] = col_data.uni_val.apply(len)
col_data['uni_vals_str'] = col_data.uni_val.astype(str)
col_data = col_data.drop('uni_val', axis=1)

# Only 1 unique value present for all rows in column
col_data.loc[col_data['n_uni_vals']==1,'var_type'] = 'drop'
# Doesn't give any useful information
col_data.loc[['encounter_id'],['var_type']] = 'drop'
col_data.loc[['patient_nbr'],['var_type']] = 'drop'
col_data.loc[['payer_code'],['var_type']] = 'drop'
# Remove weight column as most of the values are empty
col_data.loc[['weight'],['var_type']] = 'drop'
# Remove Speciality column as we already converted each value to true false columns
col_data.loc[['medical_specialty'],['var_type']] = 'drop'
# Remove diagnosis columns as we already convertd each value to true false columns
col_data.loc[['diag_1'],['var_type']] = 'drop'
col_data.loc[['diag_2'],['var_type']] = 'drop'
col_data.loc[['diag_3'],['var_type']] = 'drop'

col_data.loc[['num_procedures'],['var_type']] = 'cont'
col_data.loc[['age'],['var_type']] = 'cont'
col_data.loc[['time_in_hospital'],['var_type']] = 'cont'
col_data.loc[['number_emergency'],['var_type']] = 'cont'
col_data.loc[['number_inpatient'],['var_type']] = 'cont'
col_data.loc[['number_diagnoses'],['var_type']] = 'cont'
col_data.loc[['number_outpatient'],['var_type']] = 'cont'
col_data.loc[['num_medications'],['var_type']] = 'cont'
col_data.loc[['num_lab_procedures'],['var_type']] = 'cont'

col_data.loc[['readmitted'],['var_type']] = 'class'

col_data.loc[col_data.var_type.isnull(),'var_type'] = 'cat'
col_data

,nan_rat,n_uni_vals,uni_vals_str,var_type
encounter_id,0.000000,101766,"set([77856768, 173015040, 291198294, 84934662,...",drop
patient_nbr,0.000000,71518,"set([33947649, 92667906, 86507721, 82706436, 8...",drop
race,0.022336,6,"set([nan, 'AfricanAmerican', 'Hispanic', 'Othe...",cat
gender,0.000000,3,"set(['Male', 'Unknown/Invalid', 'Female'])",cat
age,0.000000,10,"set(['[10-20)', '[80-90)', '[70-80)', '[60-70)...",cont
weight,0.968585,10,"set([nan, '[75-100)', '[125-150)', '[175-200)'...",drop
admission_type_id,0.000000,8,"set([1, 2, 3, 4, 5, 6, 7, 8])",cat
discharge_disposition_id,0.000000,26,"set([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13...",cat
admission_source_id,0.000000,17,"set([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 13, 14...",cat
time_in_hospital,0.000000,14,"set([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13...",cont
payer_code,0.395574,18,"set([nan, 'MD', 'FR', 'DM', 'WC', 'CM', 'MC', ...",drop
medical_specialty,0.490822,73,"set([nan, 'Anesthesiology-Pediatric', 'Radiolo...",drop
num_lab_procedures,0.000000,118,"set([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13...",cont
num_procedures,0.000000,7,"set([0, 1, 2, 3, 4, 5, 6])",cont
num_medications,0.000000,75,"set([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13...",cont
number_outpatient,0.000000,39,"set([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,...",cont
number_emergency,0.000000,33,"set([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,...",cont
number_inpatient,0.000000,21,"set([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,...",cont
diag_1,0.000206,717,"set([nan, '344', '345', '346', '347', '340', '...",drop
diag_2,0.003518,749,"set([nan, '619', '965', '344', '345', '346', '...",drop
diag_3,0.013983,790,"set([nan, '538', '344', '345', '346', '347', '...",drop
number_diagnoses,0.000000,16,"set([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13...",cont
max_glu_serum,0.000000,4,"set(['None', '>200', '>300', 'Norm'])",cat
A1Cresult,0.000000,4,"set(['>8', 'None', 'Norm', '>7'])",cat
metformin,0.000000,4,"set(['Down', 'Steady', 'Up', 'No'])",cat
repaglinide,0.000000,4,"set(['Down', 'Steady', 'Up', 'No'])",cat
nateglinide,0.000000,4,"set(['Down', 'Steady', 'Up', 'No'])",cat
chlorpropamide,0.000000,4,"set(['Down', 'Steady', 'Up', 'No'])",cat
glimepiride,0.000000,4,"set(['Down', 'Steady', 'Up', 'No'])",cat
acetohexamide,0.000000,2,"set(['Steady', 'No'])",cat
glipizide,0.000000,4,"set(['Down', 'Steady', 'Up', 'No'])",cat
glyburide,0.000000,4,"set(['Down', 'Steady', 'Up', 'No'])",cat
tolbutamide,0.000000,2,"set(['Steady', 'No'])",cat
pioglitazone,0.000000,4,"set(['Down', 'Steady', 'Up', 'No'])",cat
rosiglitazone,0.000000,4,"set(['Down', 'Steady', 'Up', 'No'])",cat
acarbose,0.000000,4,"set(['Down', 'Steady', 'Up', 'No'])",cat
miglitol,0.000000,4,"set(['Down', 'Steady', 'Up', 'No'])",cat
troglitazone,0.000000,2,"set(['Steady', 'No'])",cat
tolazamide,0.000000,3,"set(['Steady', 'Up', 'No'])",cat
examide,0.000000,1,set(['No']),drop
citoglipton,0.000000,1,set(['No']),drop
insulin,0.000000,4,"set(['Down', 'Steady', 'Up', 'No'])",cat
glyburide-metformin,0.000000,4,"set(['Down', 'Steady', 'Up', 'No'])",cat
glipizide-metformin,0.000000,2,"set(['Steady', 'No'])",cat
glimepiride-pioglitazone,0.000000,2,"set(['Steady', 'No'])",cat
metformin-rosiglitazone,0.000000,2,"set(['Steady', 'No'])",cat
metformin-pioglitazone,0.000000,2,"set(['Steady', 'No'])",cat
change,0.000000,2,"set(['Ch', 'No'])",cat
diabetesMed,0.000000,2,"set(['Yes', 'No'])",cat
readmitted,0.000000,3,"set(['>30', '<30', 'NO'])",class

df_raw.medical_specialty.value_counts()

In [45]:
df_raw.medical_specialty.value_counts()

InternalMedicine                     14635
Emergency/Trauma                      7565
Family/GeneralPractice                7440
Cardiology                            5352
Surgery-General                       3099
Nephrology                            1613
Orthopedics                           1400
Orthopedics-Reconstructive            1233
Radiologist                           1140
Pulmonology                            871
Psychiatry                             854
Urology                                685
ObstetricsandGynecology                671
Surgery-Cardiovascular/Thoracic        652
Gastroenterology                       564
Surgery-Vascular                       533
Surgery-Neuro                          468
PhysicalMedicineandRehabilitation      391
Oncology                               348
Pediatrics                             254
Hematology/Oncology                    207
Neurology                              203
Pediatrics-Endocrinology               159
Otolaryngology                         125
Endocrinology                          120
Surgery-Thoracic                       109
Psychology                             101
Podiatry                               100
Surgery-Cardiovascular                  98
Pediatrics-CriticalCare                 87
                                     ...
Anesthesiology-Pediatric                19
Obstetrics                              19
Pathology                               17
Rheumatology                            17
Anesthesiology                          12
OutreachServices                        12
Surgery-Maxillofacial                   11
PhysicianNotFound                       11
Surgery-Colon&Rectal                    11
Pediatrics-Neurology                    10
Endocrinology-Metabolism                 8
Surgery-Pediatric                        8
AllergyandImmunology                     7
Psychiatry-Child/Adolescent              7
Cardiology-Pediatric                     7
DCPTEAM                                  6
Dentistry                                4
Pediatrics-Hematology-Oncology           4
Pediatrics-AllergyandImmunology          3
Pediatrics-EmergencyMedicine             3
Resident                                 2
Speech                                   1
Surgery-PlasticwithinHeadandNeck         1
Perinatology                             1
Proctology                               1
Pediatrics-InfectiousDiseases            1
Dermatology                              1
Psychiatry-Addictive                     1
Neurophysiology                          1
SportsMedicine                           1
Name: medical_specialty, Length: 72, dtype: int64

In [46]:
df_raw

,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,...,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
0,2278392,8222157,Caucasian,Female,[0-10),NaN,6,25,1,1,...,No,No,No,No,No,No,No,No,No,NO
1,149190,55629189,Caucasian,Female,[10-20),NaN,1,1,7,3,...,No,Up,No,No,No,No,No,Ch,Yes,>30
2,64410,86047875,AfricanAmerican,Female,[20-30),NaN,1,1,7,2,...,No,No,No,No,No,No,No,No,Yes,NO
3,500364,82442376,Caucasian,Male,[30-40),NaN,1,1,7,2,...,No,Up,No,No,No,No,No,Ch,Yes,NO
4,16680,42519267,Caucasian,Male,[40-50),NaN,1,1,7,1,...,No,Steady,No,No,No,No,No,Ch,Yes,NO
5,35754,82637451,Caucasian,Male,[50-60),NaN,2,1,2,3,...,No,Steady,No,No,No,No,No,No,Yes,>30
6,55842,84259809,Caucasian,Male,[60-70),NaN,3,1,2,4,...,No,Steady,No,No,No,No,No,Ch,Yes,NO
7,63768,114882984,Caucasian,Male,[70-80),NaN,1,1,7,5,...,No,No,No,No,No,No,No,No,Yes,>30
8,12522,48330783,Caucasian,Female,[80-90),NaN,2,1,4,13,...,No,Steady,No,No,No,No,No,Ch,Yes,NO
9,15738,63555939,Caucasian,Female,[90-100),NaN,3,3,4,12,...,No,Steady,No,No,No,No,No,Ch,Yes,NO
10,28236,89869032,AfricanAmerican,Female,[40-50),NaN,1,1,7,9,...,No,Steady,No,No,No,No,No,No,Yes,>30
11,36900,77391171,AfricanAmerican,Male,[60-70),NaN,2,1,4,7,...,No,Steady,No,No,No,No,No,Ch,Yes,<30
12,40926,85504905,Caucasian,Female,[40-50),NaN,1,3,7,7,...,No,Down,No,No,No,No,No,Ch,Yes,<30
13,42570,77586282,Caucasian,Male,[80-90),NaN,1,6,7,10,...,No,Steady,No,No,No,No,No,No,Yes,NO
14,62256,49726791,AfricanAmerican,Female,[60-70),NaN,3,1,2,1,...,No,Steady,No,No,No,No,No,No,Yes,>30
15,73578,86328819,AfricanAmerican,Male,[60-70),NaN,1,3,7,12,...,No,Up,No,No,No,No,No,Ch,Yes,NO
16,77076,92519352,AfricanAmerican,Male,[50-60),NaN,1,1,7,4,...,No,Steady,No,No,No,No,No,Ch,Yes,<30
17,84222,108662661,Caucasian,Female,[50-60),NaN,1,1,7,3,...,No,No,No,No,No,No,No,No,Yes,NO
18,89682,107389323,AfricanAmerican,Male,[70-80),NaN,1,1,7,5,...,No,Steady,No,No,No,No,No,No,Yes,>30
19,148530,69422211,NaN,Male,[70-80),NaN,3,6,2,6,...,No,Steady,No,No,No,No,No,Ch,Yes,NO
20,150006,22864131,NaN,Female,[50-60),NaN,2,1,4,2,...,No,Down,No,No,No,No,No,Ch,Yes,NO
21,150048,21239181,NaN,Male,[60-70),NaN,2,1,4,2,...,No,Steady,No,No,No,No,No,Ch,Yes,NO
22,182796,63000108,AfricanAmerican,Female,[70-80),NaN,2,1,4,2,...,No,No,No,No,No,No,No,No,No,NO
23,183930,107400762,Caucasian,Female,[80-90),NaN,2,6,1,11,...,No,No,No,No,No,No,No,No,No,>30
24,216156,62718876,AfricanAmerican,Female,[70-80),NaN,3,1,2,3,...,No,Steady,No,No,No,No,No,Ch,Yes,NO
25,221634,21861756,Other,Female,[50-60),NaN,1,1,7,1,...,No,No,No,No,No,No,No,No,Yes,NO
26,236316,40523301,Caucasian,Male,[80-90),NaN,1,3,7,6,...,No,No,No,No,No,No,No,Ch,Yes,NO
27,248916,115196778,Caucasian,Female,[50-60),NaN,1,1,1,2,...,No,Steady,No,No,No,No,No,No,Yes,>30
28,250872,41606064,Caucasian,Male,[20-30),NaN,2,1,2,10,...,No,Down,No,No,No,No,No,Ch,Yes,>30
29,252822,18196434,Caucasian,Female,[80-90),NaN,1,2,7,5,...,No,No,No,No,No,No,No,Ch,Yes,>30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101736,443739152,90751788,Caucasian,Female,[60-70),NaN,1,3,7,8,...,No,Steady,No,No,No,No,No,No,Yes,>30
101737,443775086,125764160,Caucasian,Female,[40-50),NaN,3,1,1,4,...,No,Steady,No,No,No,No,No,Ch,Yes,NO
101738,443775482,95780439,Caucasian,Male,[70-80),NaN,1,1,7,1,...,No,No,No,No,No,No,No,No,Yes,NO
101739,443775740,30656952,AfricanAmerican,Male,[70-80),NaN,1,1,7,1,...,No,Steady,No,No,No,No,No,No,Yes,NO
101740,443778398,134647673,Caucasian,Male,[40-50),NaN,3,1,1,1,...,No,Steady,No,No,No,No,No,Ch,Yes,NO
101741,443787128,58160520,AfricanAmerican,Male,[90-100),NaN,1,3,7,4,...,No,No,No,No,No,No,No,No,No,NO
101742,443787512,52419276,Caucasian,Male,[70-80),NaN,2,6,2,4,...,No,Steady,No,No,No,No,No,Ch,Yes,NO
101743,443793668,47293812,Caucasian,Male,[80-90),NaN,1,13,7,3,...,No,Down,No,No,No,No,No,Ch,Yes,NO
101744,443793992,43686936,Caucasian,Female,[80-90),NaN,1,1,7,1,...,No,No,No,No,No,No,No,No,No,NO
101745,443797076,183766055,Caucasian,Male,[50-60),NaN,2,1,1,3,...,No,No,No,No,No,No,No,Ch,Yes,NO
101746,443797298,89955270,Caucasian,Male,[70-80),NaN,1,1,7,4,...,No,No,No,No,No,No,No,No,Yes,<30
101747,443804570,33230016,Caucasian,Female,[70-80),NaN,1,22,7,8,...,No,Steady,No,No,No,No,No,No,Yes,>30
101748,443811536,189481478,Caucasian,Female,[40-50),NaN,1,4,7,14,...,No,Down,No,No,No,No,No,Ch,Yes,>30
101749,443816024,106392411,Caucasian,Female,[70-80),NaN,3,6,1,3,...,No,Steady,No,No,No,No,No,Ch,Yes,NO
101750,443824292,138784172,Caucasian,Female,[80-90),NaN,3,1,1,3,...,No,Down,No,No,No,No,No,Ch,Yes,<30
101751,443835140,175326800,Caucasian,Male,[70-80),NaN,3,6,1,13,...,No,Up,No,No,No,No,No,Ch,Yes,NO
101752,443835512,139605341,Other,Female,[40-50),NaN,3,1,1,3,...,No,Steady,No,No,No,No,No,Ch,Yes,NO
101753,443841992,184875899,Other,Male,[40-50),NaN,1,1,7,13,...,No,Down,No,No,No,No,No,Ch,Yes,NO
101754,443842016,183087545,Caucasian,Female,[70-80),NaN,1,1,7,9,...,No,Steady,No,No,No,No,No,Ch,Yes,>30
101755,443842022,188574944,Other,Female,[40-50),NaN,1,1,7,14,...,No,Up,No,No,No,No,No,Ch,Yes,>30
101756,443842070,140199494,Other,Female,[60-70),NaN,1,1,7,2,...,No,Steady,No,No,No,No,No,No,Yes,>30
101757,443842136,181593374,Caucasian,Female,[70-80),NaN,1,1,7,5,...,No,Steady,No,No,No,No,No,No,Yes,NO
101758,443842340,120975314,Caucasian,Female,[80-90),NaN,1,1,7,5,...,No,Up,No,No,No,No,No,Ch,Yes,NO
101759,443842778,86472243,Caucasian,Male,[80-90),NaN,1,1,7,1,...,No,Up,No,No,No,No,No,Ch,Yes,NO
101760,443847176,50375628,AfricanAmerican,Female,[60-70),NaN,1,1,7,6,...,No,Down,No,No,No,No,No,Ch,Yes,>30
101761,443847548,100162476,AfricanAmerican,Male,[70-80),NaN,1,3,7,3,...,No,Down,No,No,No,No,No,Ch,Yes,>30
101762,443847782,74694222,AfricanAmerican,Female,[80-90),NaN,1,4,5,5,...,No,Steady,No,No,No,No,No,No,Yes,NO
101763,443854148,41088789,Caucasian,Male,[70-80),NaN,1,1,7,1,...,No,Down,No,No,No,No,No,Ch,Yes,NO
101764,443857166,31693671,Caucasian,Female,[80-90),NaN,2,3,7,10,...,No,Up,No,No,No,No,No,Ch,Yes,NO
101765,443867222,175429310,Caucasian,Male,[70-80),NaN,1,1,7,6,...,No,No,No,No,No,No,No,No,No,NO